name = "Ear Plugs";
picture = "EarPlugs/logos/modIcon.edds";
logo = "EarPlugs/logos/modIcon.edds";
logoSmall = "EarPlugs/logos/modIcon.edds";
logoOver = "EarPlugs/logos/modIcon.edds";
overview = "$STR_EARPLUGS_MOD_DESCRIPTION";
tooltip = "$STR_EARPLUGS_MOD_TOOLTIP";
action = "https://steamcommunity.com/sharedfiles/filedetails/?id=1819514788";
author = "Cooltrain";
authorID = "76561198023797229";
version = "2.3";